name: Gray Performs
favicon: null
layout_spectrum: 0.6943902208004147
typography_spectrum: 0.882977040251717
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.0515670704189688
  lightness: 0.8597786666359752
  saturation: 0.6984552373178303
  rhythmicContrast: 0.11968134972266853
purpose: []
